[project]
name = "ai-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ritom Paul", email = "rittmann007@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "fpdf2>=2.8.8",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "langchain-google-genai>=4.4.0",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "notebook>=7.6.2",
    "onnxruntime>=1.29.0",
    "pandas>=3.0.5",
    "pymongo>=4.18.0",
    "pypdf>=6.17.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.63.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
ai-python = "ai_python:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
